homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:Home }

espace_etudiant:
    path:     /espace-etudiant
    defaults: { _controller: AppBundle:EspaceEtudiant:index }

inscription:
    path:     /inscription
    defaults: { _controller: AppBundle:EspaceLyceen:inscription }

presentation:
    path:     /presentation
    defaults: { _controller: AppBundle:Presentation:index }

programmes:
    path:     /programmes
    defaults: { _controller: AppBundle:Programmes:index }

cgv:
    path:     /cgv
    defaults: { _controller: AppBundle:Mentions:CGV }

mentions_legales:
    path:     /mentions_legales
    defaults: { _controller: AppBundle:Mentions:mentionsLegales }

temoignages:
    path:     /temoignages
    defaults: { _controller: AppBundle:Temoignages:index }

liste_inscrits:
    path:     /admin/users
    defaults: { _controller: AppBundle:Admin:users }
